### ISSUE TITLE
Cannot open fast5 or other errors: NA12878/fast5_files/DEAMERNANOPORE_20161206_FNFAB49164   19298 _MN16450_sequencing_run_MA_821_R9_4_NA12878_12_06_16_71094_ch228_read14558_strand.fast5

### ISSUE THREAD

**Issue by forrwill** [WGLab/DeepMod#10]
I met a question that "can not open fast5 or other errors". Could you please tell me what I should do to deal with this question? thank you!

**Comment by liujiazhe** [comment]
![image](https://user-images.githubusercontent.com/41096851/59014273-d0a89500-886e-11e9-9a05-785be3817ab7.png)
there is the log infotmation!

**Comment by liujiazhe** [comment]
![image](https://user-images.githubusercontent.com/41096851/59014318-e6b65580-886e-11e9-9124-35b6e0432ce2.png)
there is the log information, and the fast5 PATH is existed.

**Comment by liuqianhn** [comment]
Hi @liujiazhe , the log file in your screen snapshot contain no error. Could you please provide the command you used, and the full log file? Thank you very much. You can also feel free to send the full log and commands you have to liuqianhn@hotmail.com.

**Comment by liujiazhe** [comment]
Thanks for you reply, and  now ,the software has been output some results, but I still have some question about the software, such the ouput log file of "Cannot open fast5 or other errors:", and I have confirmed that the path of fast5 file is existed! Is it a error?
![image](https://user-images.githubusercontent.com/41096851/59179097-94897300-8b93-11e9-989c-5ac0c7a60073.png)

**Comment by liuqianhn** [comment]
HI @liujiazhe , could you please send me a fast5 file to check? If the files exist, it seems there are other incompatible issues. Thank you.

**Comment by liujiazhe** [comment]
the fast5 file which can not be opened is in attachment, thank you!


------------------ 原始邮件 ------------------
发件人: "liuqianhn"<notifications@github.com>;
发送时间: 2019年6月10日(星期一) 晚上10:27
收件人: "WGLab/DeepMod"<DeepMod@noreply.github.com>;
抄送: "1197364078"<1197364078@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [WGLab/DeepMod] Cannot open fast5 or other errors:NA12878/fast5_files/DEAMERNANOPORE_20161206_FNFAB49164   19298_MN16450_sequencing_run_MA_821_R9_4_NA12878_12_06_16_71094_ch228_read14558_strand.fast5(#10)




HI @liujiazhe , could you please send me a fast5 file to check? If the files exist, it seems there are other incompatible issues. Thank you.

**Comment by liuqianhn** [comment]
Hi @liujiazhe , I am sorry that I  do not see the attachment. Could you please send it to liuqianhn@hotmail.com? Thank you very much.

**Comment by liujiazhe** [comment]
Hi，Mr Liu
    now,I have got some result, output with bed format, which shows as below, could you please explain each column for me? I am not sure about the meaning of some columns.
![image](https://user-images.githubusercontent.com/41096851/59316611-e2b48880-8cf1-11e9-8c9f-e5835e295d63.png)

**Comment by liuqianhn** [comment]
Hi @liujiazhe , please refer to [results explanation](https://github.com/WGLab/DeepMod/blob/master/docs/Results_explanation.md) for detail.

**Comment by liuqianhn** [comment]
Hi @liujiazhe , I checked your fast5 file, and it seems that no 'events' information is available. The errors would be gone after using albacove for basecalling.

**Comment by liujiazhe** [comment]
thanks for you help!
I am reading your article, which was published in NC. It seems that DeepMod have little species specificity? and it is more correlative with the basecalling software? I find that the accuracy of methylation accuracy, which was calling by DeepMod, is still high, when using Ecoli training model for NA12878 5mC calling?
I am planning to use this software for plants and animals, and I want to know that if the model in software, which is downloaded is github, can be applied to other species, such as other plants and animals?

**Comment by liuqianhn** [comment]
Hi @fortwill, we do not see species specificity issue in DeepMod so far. Instead, cross-species evaluation demonstrates accurate predictions of 5mC(In the paper, we tested 5mC prediction on NA12878 when DeepMod was trained on Ecoli, and also tested 5mC prediction on Ecoli when DeepMod was trained on NA12878. Both shows highly accurate predictions). But DeepMod's performance might be affected by datasets with different basecalling softwares/versions. 
The models in github would be used for other species whose datasets were basecalling ideally with the same version of basecalling tools.

**Comment by fortwill** [comment]
Thanks for your explanation  sincerely. It helped a lot.
