### ISSUE TITLE
the output format of detect module

### ISSUE THREAD

**Issue by PengNi** [WGLab/DeepMod#13]
Hi @liuqianhn ,

Can you give more detail about the output format of  `detect` function? I don't totally understand the meaning of all 12 columns of the BED file, especially the last 3 columns.

Thank you in advance.

Best,
Peng

**Comment by liuqianhn** [comment]
Hi @PengNi , please check [results explanation](https://github.com/WGLab/DeepMod/blob/master/docs/Results_explanation.md).

**Comment by PengNi** [comment]
Thank you. Now closing the issue.
