### ISSUE TITLE
Question about the format of output

### ISSUE THREAD

**Issue by DAVID2022** [WGLab/DeepMod#14]
Can you tell me the difference between ["Capped coverage" and "Real coverage "](https://github.com/WGLab/DeepMod/blob/master/docs/Results_explanation.md) ? Is there a quality control process to filter  "Capped coverage" into "Real coverage " like nanopolish?

**Comment by liuqianhn** [comment]
Hi @DAVID2022 , sorry for the late reply. In the current output, there is no quality control process yet. Capped coverage is capped by 1000 as defined in the bed format, and real coverage is the coverage for a specific position in a genome.

**Comment by DAVID2022** [comment]
Thank you very much!
