### ISSUE TITLE
Model Training: Parameters and model metrics

### ISSUE THREAD

**Issue by cednotsed** [WGLab/DeepMod#17]
Hi,

May I ask what is the meaning of the parameters --fulmod, --anymod, and --nomod for the getfeatures option? I am trying to train a custom model but am not sure what to pass in for these parameters. Also is there any possible option to specify an output for model metrics after training?

Thanks.

**Comment by mmingay2** [comment]
I am also curious about these parameters and training a custom model in general.

thanks.

**Comment by liuqianhn** [comment]
Hi @cednotsed , @mmingay2 , there are several steps to do that, but not in a single commands, and also depend on your computing resources. I would like to collaborate with you for training custom model if you want.

**Comment by liuqianhn** [comment]
No further update and thus I close it. Feel free to re-open it if any help is needed.
