### ISSUE TITLE
Can DeepMod support multi-fast5 files?

### ISSUE THREAD

**Issue by gongyh** [WGLab/DeepMod#18]
DeepMod gives out "Error!!! Channel information could not be found in UniqueGlobalKey/channel_id  in ..." error when i use multi-fast5 files as input, but when i split them using "multi_to_single_fast5", it cannot detect events file the generated single fast5 files. 
Should i redo basecalling after spliting multi-fast5? Or there are other potential issues?

**Comment by liuqianhn** [comment]
Hi @gongyh , DeepMod does not support multi-fast5 now. One possible solution is to use ONT API to convert multi-fast5 to single fast5, and then re-basecall them. I have been working on the improvement version to support multi-fast5, but I cannot make it publicly available soon.
Feel free to let me know if you have more questions.

**Comment by gongyh** [comment]
Thanks for your quick reply. I will re-basecall those splitted fast5 using albacore and try again.
