### ISSUE TITLE
No Channel Info

### ISSUE THREAD

**Issue by Zhenhuiz** [WGLab/DeepMod#21]
Hi,

I got 2 error messages:

1   /miniconda3/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

2 Error!!! No Channel Info in ./fast5_pass/PAD32019_248c10ef90f82bed1f365e2d7a0fff9f78c5cd1b_0.fast5
Error!!! Channel information could not be found in UniqueGlobalKey/channel_id  in ./fast5_pass/PAD32019_248c10ef90f82bed1f365e2d7a0fff9f78c5cd1b_0.fast5
Error!!! No Channel Info in ./fast5_pass/PAD32019_248c10ef90f82bed1f365e2d7a0fff9f78c5cd1b_1.fast5

Do you know what happened? Thank you so much!

**Comment by liuqianhn** [comment]
Hi @Zhenhuiz , it seems that there is no channel information. Could you please show the top 50 lines of `h5ls -r ./fast5_pass/PAD32019_248c10ef90f82bed1f365e2d7a0fff9f78c5cd1b_0.fast5`?

**Comment by Zhenhuiz** [comment]
Hi Qian,

Thanks for your reply. The first 50 lines are:
/                        Group
/read_0006ee0c-4a9d-447f-bae7-d1676f8eed96 Group
/read_0006ee0c-4a9d-447f-bae7-d1676f8eed96/Analyses Group
/read_0006ee0c-4a9d-447f-bae7-d1676f8eed96/Analyses/Basecall_1D_000 Group
/read_0006ee0c-4a9d-447f-bae7-d1676f8eed96/Analyses/Basecall_1D_000/BaseCalled_template Group
/read_0006ee0c-4a9d-447f-bae7-d1676f8eed96/Analyses/Basecall_1D_000/BaseCalled_template/Fastq Dataset {SCALAR}
/read_0006ee0c-4a9d-447f-bae7-d1676f8eed96/Analyses/Basecall_1D_000/Summary Group
/read_0006ee0c-4a9d-447f-bae7-d1676f8eed96/Analyses/Basecall_1D_000/Summary/basecall_1d_template Group
/read_0006ee0c-4a9d-447f-bae7-d1676f8eed96/Analyses/Segmentation_000 Group
/read_0006ee0c-4a9d-447f-bae7-d1676f8eed96/Analyses/Segmentation_000/Summary Group
/read_0006ee0c-4a9d-447f-bae7-d1676f8eed96/Analyses/Segmentation_000/Summary/segmentation Group
/read_0006ee0c-4a9d-447f-bae7-d1676f8eed96/Raw Group
/read_0006ee0c-4a9d-447f-bae7-d1676f8eed96/Raw/Signal Dataset {40385/Inf}
/read_0006ee0c-4a9d-447f-bae7-d1676f8eed96/channel_id Group
/read_0006ee0c-4a9d-447f-bae7-d1676f8eed96/context_tags Group
/read_0006ee0c-4a9d-447f-bae7-d1676f8eed96/tracking_id Group
/read_001079c3-33e1-405e-ac75-2d2eafa7ef41 Group
/read_001079c3-33e1-405e-ac75-2d2eafa7ef41/Analyses Group
/read_001079c3-33e1-405e-ac75-2d2eafa7ef41/Analyses/Basecall_1D_000 Group
/read_001079c3-33e1-405e-ac75-2d2eafa7ef41/Analyses/Basecall_1D_000/BaseCalled_template Group
/read_001079c3-33e1-405e-ac75-2d2eafa7ef41/Analyses/Basecall_1D_000/BaseCalled_template/Fastq Dataset {SCALAR}
/read_001079c3-33e1-405e-ac75-2d2eafa7ef41/Analyses/Basecall_1D_000/Summary Group
/read_001079c3-33e1-405e-ac75-2d2eafa7ef41/Analyses/Basecall_1D_000/Summary/basecall_1d_template Group
/read_001079c3-33e1-405e-ac75-2d2eafa7ef41/Analyses/Segmentation_000 Group
/read_001079c3-33e1-405e-ac75-2d2eafa7ef41/Analyses/Segmentation_000/Summary Group
/read_001079c3-33e1-405e-ac75-2d2eafa7ef41/Analyses/Segmentation_000/Summary/segmentation Group
/read_001079c3-33e1-405e-ac75-2d2eafa7ef41/Raw Group
/read_001079c3-33e1-405e-ac75-2d2eafa7ef41/Raw/Signal Dataset {6302/Inf}
/read_001079c3-33e1-405e-ac75-2d2eafa7ef41/channel_id Group
/read_001079c3-33e1-405e-ac75-2d2eafa7ef41/context_tags Group, same as /read_0006ee0c-4a9d-447f-bae7-d1676f8eed96/context_tags
/read_001079c3-33e1-405e-ac75-2d2eafa7ef41/tracking_id Group, same as /read_0006ee0c-4a9d-447f-bae7-d1676f8eed96/tracking_id
/read_001ea880-5d1d-4c23-8b83-6c9bd7e6838a Group
/read_001ea880-5d1d-4c23-8b83-6c9bd7e6838a/Analyses Group
/read_001ea880-5d1d-4c23-8b83-6c9bd7e6838a/Analyses/Basecall_1D_000 Group
/read_001ea880-5d1d-4c23-8b83-6c9bd7e6838a/Analyses/Basecall_1D_000/BaseCalled_template Group
/read_001ea880-5d1d-4c23-8b83-6c9bd7e6838a/Analyses/Basecall_1D_000/BaseCalled_template/Fastq Dataset {SCALAR}
/read_001ea880-5d1d-4c23-8b83-6c9bd7e6838a/Analyses/Basecall_1D_000/Summary Group
/read_001ea880-5d1d-4c23-8b83-6c9bd7e6838a/Analyses/Basecall_1D_000/Summary/basecall_1d_template Group
/read_001ea880-5d1d-4c23-8b83-6c9bd7e6838a/Analyses/Segmentation_000 Group
/read_001ea880-5d1d-4c23-8b83-6c9bd7e6838a/Analyses/Segmentation_000/Summary Group
/read_001ea880-5d1d-4c23-8b83-6c9bd7e6838a/Analyses/Segmentation_000/Summary/segmentation Group
/read_001ea880-5d1d-4c23-8b83-6c9bd7e6838a/Raw Group
/read_001ea880-5d1d-4c23-8b83-6c9bd7e6838a/Raw/Signal Dataset {37024/Inf}
/read_001ea880-5d1d-4c23-8b83-6c9bd7e6838a/channel_id Group
/read_001ea880-5d1d-4c23-8b83-6c9bd7e6838a/context_tags Group, same as /read_0006ee0c-4a9d-447f-bae7-d1676f8eed96/context_tags
/read_001ea880-5d1d-4c23-8b83-6c9bd7e6838a/tracking_id Group, same as /read_0006ee0c-4a9d-447f-bae7-d1676f8eed96/tracking_id
/read_0022927f-4d11-4cf5-ac82-da1c496fa3aa Group
/read_0022927f-4d11-4cf5-ac82-da1c496fa3aa/Analyses Group
/read_0022927f-4d11-4cf5-ac82-da1c496fa3aa/Analyses/Basecall_1D_000 Group
/read_0022927f-4d11-4cf5-ac82-da1c496fa3aa/Analyses/Basecall_1D_000/BaseCalled_template Group

**Comment by liuqianhn** [comment]
Hi @Zhenhuiz ， it seems that your fast5 is multi-fast5 format. Right now, DeepMod cannot support it. You might refer to https://github.com/WGLab/DeepMod#future-improvement to see how to handle it and our future improvement.

**Comment by Zhenhuiz** [comment]
@liuqianhn Ok, thank you! Looking forward to seeing your update version!
