### ISSUE TITLE
Does DeepMod support 6mA detection in human sample?

### ISSUE THREAD

**Issue by benhur974** [WGLab/DeepMod#22]
Issue #1 mentioned 6mA analysis in HX1 but manuscript mentioned performance prediction of 6mA in E. coli and C. reinhardtii.

**Comment by liuqianhn** [comment]
Hi @benhur974 , DeepMod support 6mA detection. Please refer to https://github.com/WGLab/DeepMod/blob/master/docs/Description%20of%20well-trained%20models.md#13-rnn_conmoda_p100wd21_f7ne1u0_4 for the well-trained model for 6mA prediction. But please note that you can improve the 6mA prediction if you have ground-truth 6mA for a new 6mA model.

**Comment by benhur974** [comment]
Hi @liuqianhn , Thank you for the link. I did noticed you did detection on synthetic 6mA but I was hoping to see the same on native 6mA in human :).

**Comment by liuqianhn** [comment]
Hi @benhur974 , we have no trained model on human right now, since no larger data of 6mA in human is available. Please correct me if I am wrong.

**Comment by benhur974** [comment]
Not that I am aware of.

Thanks for the feedbacks!
