### ISSUE TITLE
where to download albacore v2.3+ 

### ISSUE THREAD

**Issue by Zhenhuiz** [WGLab/DeepMod#23]
Hi,

I converted multiFast5 into single fast5 with ot_fast5_api. But deepmod still can not recognize my data and said 'no event data'. So I'm thinking re-basecalling with albacore. I searched online, but can't find where to download it. Do you know where I can download it? Thank you!

**Comment by liuqianhn** [comment]
Hi @Zhenhuiz , yes, fast5 need to be basecalled with events before it is used as input of deepmod. For albacore, you can download from community.nanoporetech.com where you need registration first.

**Comment by Zhenhuiz** [comment]
Hi @liuqianhn Thank you!

I finally found it! But after re-basecalling, I still got error. 
'Error!!! No events data in ./new_basecall/workspace/pass/6/fde91fc4-aa00-4012-9ecb-0fd751c8fc7b.fast5'

Here is the fast5 file:

/                        Group
/Analyses                Group
/Analyses/Basecall_1D_000 Group
/Analyses/Basecall_1D_000/BaseCalled_template Group
/Analyses/Basecall_1D_000/BaseCalled_template/Fastq Dataset {SCALAR}
/Analyses/Basecall_1D_000/Summary Group
/Analyses/Basecall_1D_000/Summary/basecall_1d_template Group
/Analyses/Basecall_1D_001 Group
/Analyses/Basecall_1D_001/BaseCalled_template Group
/Analyses/Basecall_1D_001/BaseCalled_template/Events Dataset {1208}
/Analyses/Basecall_1D_001/BaseCalled_template/Fastq Dataset {SCALAR}
/Analyses/Basecall_1D_001/Configuration Group
/Analyses/Basecall_1D_001/Configuration/basecall_1d Group
/Analyses/Basecall_1D_001/Summary Group
/Analyses/Basecall_1D_001/Summary/basecall_1d_template Group
/Analyses/Calibration_Strand_Detection_000 Group
/Analyses/Calibration_Strand_Detection_000/Configuration Group
/Analyses/Calibration_Strand_Detection_000/Configuration/calib_detector Group
/Analyses/Calibration_Strand_Detection_000/Summary Group
/Analyses/Calibration_Strand_Detection_000/Summary/calibration_strand_template Group
/Analyses/Segmentation_000 Group
/Analyses/Segmentation_000/Summary Group
/Analyses/Segmentation_000/Summary/segmentation Group
/Analyses/Segmentation_001 Group
/Analyses/Segmentation_001/Configuration Group
/Analyses/Segmentation_001/Configuration/event_detection Group
/Analyses/Segmentation_001/Configuration/stall_removal Group
/Analyses/Segmentation_001/Summary Group
/Analyses/Segmentation_001/Summary/segmentation Group
/Raw                     Group
/Raw/Reads               Group
/Raw/Reads/Read_138      Group
/Raw/Reads/Read_138/Signal Dataset {9570/Inf}
/UniqueGlobalKey         Group
/UniqueGlobalKey/channel_id Group
/UniqueGlobalKey/context_tags Group
/UniqueGlobalKey/tracking_id Group

**Comment by liuqianhn** [comment]
Hi @Zhenhuiz, This is because the events information is not under the default path (`Basecall_1D_000`). You can use `--basecall_1d Basecall_1D_001` (This setting is assumed that events information under  `Basecall_1D_001` in all fast5 files). If events are under different paths in different files, it would be better to remove old basecall information from fast5 files before re-basecalling.

**Comment by Zhenhuiz** [comment]
Hi @liuqianhn 
Could you tell more about where should I use --basecall_1d Basecall_1D_001? In basecalling step or deepmod detect step? And how events information looks? I can only find my fast5 but I don't know where event file is. Thank you!

**Comment by liuqianhn** [comment]
Hi @Zhenhuiz , `--basecall_1d Basecall_1D_001` is a parameter for deepmod. `event` is in fast5 file. In your fast5 file, if you can see `/Analyses/Basecall_1D_001/BaseCalled_template/**Events**`, it is basecalled with event.

**Comment by liuqianhn** [comment]
No further update, and thus I close it. Feel free to re-open it if you need help.
