### ISSUE TITLE
Description for models used in different situation

### ISSUE THREAD

**Issue by chenkenbio** [WGLab/DeepMod#25]
Hello, I'm interested in your wonderful work and trying to use it, but I don't understand the difference between model files under `DeepMod/train_mod`. Could you please provide information for users to choose the most suitable model for their analyzing, or do you mean that the users should re-train the model for their work? Thank you!

**Comment by liuqianhn** [comment]
Hi @chenkenbio , please find the detail description of the model in https://github.com/WGLab/DeepMod/blob/master/docs/Description%20of%20well-trained%20models.md. If you are worked on 5mC, I would suggest using `1.5 rnn_f7_wd21_chr1to10_4` and `1.3 rnn_conmodA_P100wd21_f7ne1u0_4` for 6mA. But if you have latest data for training purpose, you can achieve better performance for your own training model.

**Comment by chenkenbio** [comment]
> Hi @chenkenbio , please find the detail description of the model in https://github.com/WGLab/DeepMod/blob/master/docs/Description%20of%20well-trained%20models.md. If you are worked on 5mC, I would suggest using `1.5 rnn_f7_wd21_chr1to10_4` and `1.3 rnn_conmodA_P100wd21_f7ne1u0_4` for 6mA. But if you have latest data for training purpose, you can achieve better performance for your own training model.

Thank you!
