### ISSUE TITLE
The index of the first base is less than -2

### ISSUE THREAD

**Issue by lemonsky123** [WGLab/DeepMod#27]
Hi @liuqianhn 
I'm running DeepMod on several fast5 files, and I got the following error
`Error!!! The index of the first base is less than -2(-12323486=0.000000*4000-12323486) in DEAMERNANOPORE_20161117_FNFAB43577_MN16450_sequencing_run_MA_821_R9_4_NA12878_11_17_16_88738_ch137_read888_strand.fast5`
The data was downloaded from [NA12878](https://github.com/nanopore-wgs-consortium/NA12878/blob/master/nanopore-human-genome/rel_3_4.md)， and was basecalled by Albacore-2.3.1 with the following command
`read_fast5_basecaller.py --input fast5 --worker 20 --save_path out --flowcell FLO-MIN106 --kit SQK-RAD002 -o fast5`
The DeepMod command used is shown below
`python DeepMod.py detect --wrkBase base_called_fast5 --Ref hg19.fa --FileID test --modfile train_mod/rnn_conmodC_P100wd21_f7ne1u0_4/mod_train_conmodC_P100wd21_f3ne1u0 --threads 15 --outFolder output`
Could you please tell me where the problem is? Thanks so much!
Best.

**Comment by liuqianhn** [comment]
Hi @lemonsky123 , it seems that there is an issue for the basecalling: no basecalling information or wrong start index for the first event. It will be helpful if you can share "DEAMERNANOPORE_20161117_FNFAB43577_MN16450_sequencing_run_MA_821_R9_4_NA12878_11_17_16_88738_ch137_read888_strand.fast5" with me so that I can check what is the exact issue.  Thanks.

**Comment by lemonsky123** [comment]
> Hi @lemonsky123 , it seems that there is an issue for the basecalling: no basecalling information or wrong start index for the first event. It will be helpful if you can share "DEAMERNANOPORE_20161117_FNFAB43577_MN16450_sequencing_run_MA_821_R9_4_NA12878_11_17_16_88738_ch137_read888_strand.fast5" with me so that I can check what is the exact issue. Thanks.

**Comment by lemonsky123** [comment]
> Hi @lemonsky123 , it seems that there is an issue for the basecalling: no basecalling information or wrong start index for the first event. It will be helpful if you can share "DEAMERNANOPORE_20161117_FNFAB43577_MN16450_sequencing_run_MA_821_R9_4_NA12878_11_17_16_88738_ch137_read888_strand.fast5" with me so that I can check what is the exact issue. Thanks.

Hi, @liuqianhn. Thanks for the reply, The fast5 files is shared below.
[Uploading DEAMERNANOPORE_20161117_FNFAB43577_MN16450_sequencing_run_MA_821_R9_4_NA12878_11_17_16_88738_ch137_read888_strand.zip…]()

**Comment by liuqianhn** [comment]
Hi @lemonsky123 , is it very large? It seems that I cannot download it now.

**Comment by lemonsky123** [comment]
Hi, @liuqianhn . The file is quite small(about 62KB). I re-upload the file below. Can you download it now?
[DEAMERNANOPORE_20161117_FNFAB43577_MN16450_sequencing_run_MA_821_R9_4_NA12878_11_17_16_88738_ch137_read888_strand.zip](https://github.com/WGLab/DeepMod/files/3911971/DEAMERNANOPORE_20161117_FNFAB43577_MN16450_sequencing_run_MA_821_R9_4_NA12878_11_17_16_88738_ch137_read888_strand.zip)

**Comment by liuqianhn** [comment]
Hi @lemonsky123 , I can download the new one. Thank you.

**Comment by lemonsky123** [comment]
> Hi @lemonsky123 , I can download the new one. Thank you.

Nice to hear that, looking forward to hearing from you again.

**Comment by liuqianhn** [comment]
Hi @lemonsky123 , I re-installed DeepMod and run the command below with your fast5 file under "for_lemonsky123". But I do not get any error. 
```
python DeepMod/bin/DeepMod.py detect --wrkBase for_lemonsky123 --Ref GRCh38/GRCh38.fa --FileID test --modfile DeepMod/train_mod/rnn_conmodC_P100wd21_f7ne1u0_4/mod_train_conmodC_P100wd21_f3ne1u0 --threads 15 --outFolder output
```

Did you install dependent packages as instructed in "https://github.com/WGLab/DeepMod/blob/master/docs/Install.md"?

**Comment by lemonsky123** [comment]
Hi @liuqianhn , Thanks for the reply. I installed all the needed packages with conda accorrding to your tutorial. Then I re-run DeepMod, but I still got the same error. The picture is shown below
![error](https://user-images.githubusercontent.com/50455057/70021464-c5d77e80-15cb-11ea-8f27-f6a1580cba26.jpg)

**Comment by liuqianhn** [comment]
Hi @lemonsky123 , it seems that there are changes in python functions, and some functions do not exist. I have fixed the issue. Could you please download the latest version and have a try? Feel free to let me know if there is any issue.

**Comment by lemonsky123** [comment]
Hi, @liuqianhn . I have downloaded the latest version of DeepMod and the error information is gone. Thanks for your help!

**Comment by lemonsky123** [comment]
Hi @liuqianhn , when I was using DeepMod for the analysis of  2000 fast5 files, I got the following error:
`mkdir: cannot create directory ‘××××’: File exists`. The  picture is shown below
![pic_20191207204652](https://user-images.githubusercontent.com/50455057/70374913-0d933880-1933-11ea-8dd2-fea70c06573d.png)
But when I reduced the files to 1500,  the error was gone, the picture is shown below
![pic_20191207204709](https://user-images.githubusercontent.com/50455057/70374953-a629b880-1933-11ea-822f-8565fcf0ebda.png)
What's more, another error was also shown in the picture, the error is 
`Error information for different fast5 files:
        Not in alignment sam ××`
Could you please help me with those problems? Thanks so much!

**Comment by liuqianhn** [comment]
Hi @lemonsky123 , you are fine. The message you are showing does not mean any error in your result.

The first error just means the folder exist and not need to create it.

The second error is to tell you that some reads cannot aligned to the reference genome. On average, you have 5% unmapped reads, which is normal. 

In short, your running is without critical error and your result is good.

**Comment by liuqianhn** [comment]
Closed due to no recent activities.
