### ISSUE TITLE
Can I use flappie guppy or taiyaki run base call process, and then running DeepMod process for methylation calling?

### ISSUE THREAD

**Issue by forrwill** [WGLab/DeepMod#28]

**Comment by liuqianhn** [comment]
@forrwill , you can use different basecaller now, but DeepMod only support single fast5 format. If your fast5 is multi-fast5 files, please use [ont_fast5_api](https://github.com/nanoporetech/ont_fast5_api) convert multi-fast5 files to single fast5 files first.

**Comment by liuqianhn** [comment]
Closed due to no recent response. Feel free to reopen it if you need more help.
