### ISSUE TITLE
 No events data in fast5

### ISSUE THREAD

**Issue by lqsae** [WGLab/DeepMod#29]
I have convert multi-fast5 to single fast5 file,
but it has the the error 
Error!!! No events data in
/mnt/CCX/User/liuqingshan/methylation/deepsignal/00.data/115.single_fast5_reads/109/c006ef2c-7bf4-432a-9e21-d1bc399c3766.fast5
can you help me?

**Comment by liuqianhn** [comment]
Hi @lqsae , could you please show me the output of `h5ls -r /mnt/CCX/User/liuqingshan/methylation/deepsignal/00.data/115.single_fast5_reads/109/c006ef2c-7bf4-432a-9e21-d1bc399c3766.fast5` (I assume this fast5 file is for a single read; otherwise, please use `head -n 50` to show the first 50 lines.).

**Comment by lqsae** [comment]
Thank you for your reply ,i have show the output .
h5ls -r /mnt/CCX/User/liuqingshan/methylation/deepsignal/00.data/115.single_fast5_reads/208/68b3db20-2afb-4c4c-b981-c18c44da18b0.fast5
/                        Group
/Analyses                Group
/Analyses/Basecall_1D_000 Group
/Analyses/Basecall_1D_000/BaseCalled_template Group
/Analyses/Basecall_1D_000/BaseCalled_template/Fastq Dataset {SCALAR}
/Analyses/Basecall_1D_000/Summary Group
/Analyses/Basecall_1D_000/Summary/basecall_1d_template Group
/Analyses/Segmentation_000 Group
/Analyses/Segmentation_000/Summary Group
/Analyses/Segmentation_000/Summary/segmentation Group
/Raw                     Group
/Raw/Reads               Group
/Raw/Reads/Read_55878    Group
/Raw/Reads/Read_55878/Signal Dataset {12552/Inf}
/UniqueGlobalKey         Group
/UniqueGlobalKey/channel_id Group
/UniqueGlobalKey/context_tags Group
/UniqueGlobalKey/tracking_id Group

**Comment by lqsae** [comment]
Thank you for your reply ,i have show the output . h5ls -r /mnt/CCX/User/liuqingshan/methylation/deepsignal/00.data/115.single_fast5_reads/208/68b3db20-2afb-4c4c-b981-c18c44da18b0.fast5
/ Group
/Analyses Group
/Analyses/Basecall_1D_000 Group
/Analyses/Basecall_1D_000/BaseCalled_template Group
/Analyses/Basecall_1D_000/BaseCalled_template/Fastq Dataset {SCALAR}
/Analyses/Basecall_1D_000/Summary Group
/Analyses/Basecall_1D_000/Summary/basecall_1d_template Group
/Analyses/Segmentation_000 Group
/Analyses/Segmentation_000/Summary Group
/Analyses/Segmentation_000/Summary/segmentation Group
/Raw Group
/Raw/Reads Group
/Raw/Reads/Read_55878 Group
/Raw/Reads/Read_55878/Signal Dataset {12552/Inf}
/UniqueGlobalKey Group
/UniqueGlobalKey/channel_id Group
/UniqueGlobalKey/context_tags Group
/UniqueGlobalKey/tracking_id Group

| |
刘青山
|
|
邮箱：18637315793@163.com
|

签名由 网易邮箱大师 定制

On 12/18/2019 22:22, liuqianhn wrote:

Hi @lqsae , could you please show me the output of h5ls -r /mnt/CCX/User/liuqingshan/methylation/deepsignal/00.data/115.single_fast5_reads/109/c006ef2c-7bf4-432a-9e21-d1bc399c3766.fast5 (I assume this fast5 file is for a single read; otherwise, please use head -n 50 to show the first 50 lines.).

**Comment by liuqianhn** [comment]
Hi @lqsae , from your output, I do not find `Event` or `Move` in the fast5 file, and this is why this fast5 file has an issue. But it is normal if you have thousands of fast5 files and only tens of them have some issues in fast5.

**Comment by lqsae** [comment]
tank you very much , i have got it。


| |
刘青山
|
|
18637315793@163.com
|
签名由网易邮箱大师定制
On 12/18/2019 23:42，liuqianhn<notifications@github.com> wrote：

Hi @lqsae , from your output, I do not find Event or Move in the fast5 file, and this is why this fast5 file has an issue. But it is normal if you have thousands of fast5 files and only tens of them have some issues in fast5.

**Comment by lqsae** [comment]
I have run the program, but my result is empy。
 I find that all  my fast5 files don't contain  move or evnet  ,how can i solve the problem ?

**Comment by liuqianhn** [comment]
@lqsae , you can try albacore with the parameter of "--output_format fast5,fastq" and usually, `event` will be output.

**Comment by lqsae** [comment]
Hi !
the  fast5 files  contain evnet, but it stiil "Error!!! No events data in /mnt/CCX/User/liuqingshan/basecall/115/workspace/pass/0/48bc46de-0d8d-4800-8239-862fadcd082a.fast5"

h5ls -r /mnt/CCX/User/liuqingshan/basecall/115/workspace/pass/0/48bc46de-0d8d-4800-8239-862fadcd082a.fast5
/                        Group
/Analyses                Group
/Analyses/Basecall_1D_000 Group
/Analyses/Basecall_1D_000/BaseCalled_template Group
/Analyses/Basecall_1D_000/BaseCalled_template/Fastq Dataset {SCALAR}
/Analyses/Basecall_1D_000/Summary Group
/Analyses/Basecall_1D_000/Summary/basecall_1d_template Group
/Analyses/Basecall_1D_001 Group
/Analyses/Basecall_1D_001/BaseCalled_template Group
/Analyses/Basecall_1D_001/BaseCalled_template/Events Dataset {4798}
/Analyses/Basecall_1D_001/BaseCalled_template/Fastq Dataset {SCALAR}
/Analyses/Basecall_1D_001/Configuration Group
/Analyses/Basecall_1D_001/Configuration/basecall_1d Group
/Analyses/Basecall_1D_001/Summary Group
/Analyses/Basecall_1D_001/Summary/basecall_1d_template Group
/Analyses/Calibration_Strand_Detection_000 Group
/Analyses/Calibration_Strand_Detection_000/Configuration Group
/Analyses/Calibration_Strand_Detection_000/Configuration/calib_detector Group
/Analyses/Calibration_Strand_Detection_000/Summary Group
/Analyses/Calibration_Strand_Detection_000/Summary/calibration_strand_template Group
/Analyses/RawGenomeCorrected_000 Group
/Analyses/RawGenomeCorrected_000/BaseCalled_template Group
/Analyses/RawGenomeCorrected_000/BaseCalled_template/Alignment Group
/Analyses/RawGenomeCorrected_000/BaseCalled_template/Events Dataset {1922}
/Analyses/RawGenomeCorrected_001 Group
/Analyses/RawGenomeCorrected_001/BaseCalled_template Group
/Analyses/RawGenomeCorrected_001/BaseCalled_template/Alignment Group
/Analyses/RawGenomeCorrected_001/BaseCalled_template/Events Dataset {2476}
/Analyses/Segmentation_000 Group
/Analyses/Segmentation_000/Summary Group
/Analyses/Segmentation_000/Summary/segmentation Group
/Analyses/Segmentation_001 Group
/Analyses/Segmentation_001/Configuration Group
/Analyses/Segmentation_001/Configuration/stall_removal Group
/Analyses/Segmentation_001/Summary Group

**Comment by liuqianhn** [comment]
Hi @lqsae , by default, the event is under `Basecall_1D_000`, while your event is under `Basecall_1D_001`. You might use `--basecall_1d Basecall_1D_001` to set the event path for your fast5 file.

**Comment by lqsae** [comment]
tank you

**Comment by liu2005678** [comment]
Hi, Dear @liuqianhn ,  you mentioned that either " Event or Move in the fast5 file" is acceptable for Deepmod, however, in my case,  it continuously complained thing like  "Error!!! No events data in ./44d5ad5e-3937-40c3-9411-eb93a0d3a148.fast5" . (guppy_basecaller version 3.4.5+fb1fbfb was used for basecalling and single fast5 was generate with ont_fast5_api, no "Event" tag). A command line using " h5ls -r 44d5ad5e-3937-40c3-9411-eb93a0d3a148.fast5" showed that it has the "Move" tag, as follows：
/                        Group
/Analyses                Group
/Analyses/Basecall_1D_000 Group
/Analyses/Basecall_1D_000/BaseCalled_template Group
/Analyses/Basecall_1D_000/BaseCalled_template/Fastq Dataset {SCALAR}
/Analyses/Basecall_1D_000/BaseCalled_template/Move Dataset {36010}
/Analyses/Basecall_1D_000/BaseCalled_template/Trace Dataset {36010, 8}
/Analyses/Basecall_1D_000/Summary Group
/Analyses/Basecall_1D_000/Summary/basecall_1d_template Group
/Analyses/Basecall_1D_001 Group
/Analyses/Basecall_1D_001/BaseCalled_template Group
/Analyses/Basecall_1D_001/BaseCalled_template/Fastq Dataset {SCALAR}
/Analyses/Basecall_1D_001/BaseCalled_template/Move Dataset {36010}
/Analyses/Basecall_1D_001/BaseCalled_template/Trace Dataset {36010, 8}
/Analyses/Basecall_1D_001/Summary Group
/Analyses/Basecall_1D_001/Summary/basecall_1d_template Group
/Analyses/RawGenomeCorrected_000 Group
/Analyses/RawGenomeCorrected_000/BaseCalled_template Group
/Analyses/RawGenomeCorrected_000/BaseCalled_template/Alignment Group
/Analyses/RawGenomeCorrected_000/BaseCalled_template/Events Dataset {14780}
/Analyses/Segmentation_000 Group
/Analyses/Segmentation_000/Summary Group
/Analyses/Segmentation_000/Summary/segmentation Group
/Analyses/Segmentation_001 Group
/Analyses/Segmentation_001/Summary Group
/Analyses/Segmentation_001/Summary/segmentation Group
/Raw                     Group
/Raw/Reads               Group
/Raw/Reads/Read_696      Group
/Raw/Reads/Read_696/Signal Dataset {144829/Inf}
/UniqueGlobalKey         Group
/UniqueGlobalKey/channel_id Group
/UniqueGlobalKey/context_tags Group
/UniqueGlobalKey/tracking_id Group

should my datasets suitable for Deepmod, how to add the events. please!

**Comment by liuqianhn** [comment]
@lqsae , I guess you might not change the setting of `--move` which will use move table. By default, the value of `--move` is false, indicating event table is used. Could you please share the commands and this single fast5 file if you have set `--move`?

**Comment by liu2005678** [comment]
there is no "--move" options in guppy_basecaller. the command I used is

 guppy_basecaller -i /media/logen/PanD/Data/ -r -s /media/logen/PanE/aba_barcoded/ -x cuda:0 -c dna_r9.4.1_450bps_hac.cfg --num_callers 1 --gpu_runners_per_device 8 --chunks_per_runner 160 --fast5_out  --barcode_kits SQK-RBK004 --trim_barcodes 

And I checked the **dna_r9.4.1_450bps_hac.cfg**, it writes:

# Basic configuration file for ONT Guppy basecaller software.

# Compatibility
compatible_flowcells                = FLO-FLG001,FLO-MIN106
compatible_kits                     = SQK-CAS109,SQK-DCS108,SQK-DCS109,SQK-LRK001,SQK-LSK108,SQK-LSK109,SQK-LSK109-XL,SQK-LWP001,SQK-PCS108,SQK-PCS109,SQK-PRC109,SQK-PSK004,SQK-RAD002,SQK-RAD003,SQK-RAD004,SQK-RAS201,SQK-RLI001,VSK-VBK001,VSK-VSK001,VSK-VSK002
compatible_kits_with_barcoding      = SQK-16S024,SQK-PCB109,SQK-RBK001,SQK-RBK004,SQK-RLB001,SQK-LWB001,SQK-PBK004,SQK-RAB201,SQK-RAB204,SQK-RPB004,VSK-VMK001,VSK-VMK002

# Data trimming.
trim_strategy                       = dna
trim_threshold                      = 2.5
trim_min_events                     = 3

# Basecalling.
model_file                          = template_r9.4.1_450bps_hac.jsn
chunk_size                          = 1000
gpu_runners_per_device              = 4
chunks_per_runner                   = 512
chunks_per_caller                   = 10000
overlap                             = 50
qscore_offset                       = 0.284
qscore_scale                        = 0.884
builtin_scripts                     = 1

# Calibration strand detection
calib_reference                     = lambda_3.6kb.fasta
calib_min_sequence_length           = 3000
calib_max_sequence_length           = 3800
calib_min_coverage                  = 0.6

# Output.
records_per_fastq                   = 4000
min_qscore                          = 7.0

# Telemetry
ping_url                            = https://ping.oxfordnanoportal.com/basecall
ping_segment_duration               = 60


The single fast5 file was used with multi_to_single_fast5, only -i -s -t -r options were set. 
a fast5 file was attached. with gzipped
[0ae47c9f-cb82-4312-ab12-cc884b39e1a0.fast5.gz](https://github.com/WGLab/DeepMod/files/4148452/0ae47c9f-cb82-4312-ab12-cc884b39e1a0.fast5.gz)

**Comment by liuqianhn** [comment]
Hi @lqsae , I was talking about `--move` setting in DeepMod.

**Comment by liu2005678** [comment]
much thanks

**Comment by liu2005678** [comment]
By the way, some of my reads could not find channels by Deepmod, h5ls -r shows that:
/read_d5df4431-8315-4983-835a-61c4d54c4d0a Group
/read_d5df4431-8315-4983-835a-61c4d54c4d0a/Analyses Group
/read_d5df4431-8315-4983-835a-61c4d54c4d0a/Analyses/Basecall_1D_000 Group
/read_d5df4431-8315-4983-835a-61c4d54c4d0a/Analyses/Basecall_1D_000/BaseCalled_template Group
/read_d5df4431-8315-4983-835a-61c4d54c4d0a/Analyses/Basecall_1D_000/BaseCalled_template/Fastq Dataset {SCALAR}
/read_d5df4431-8315-4983-835a-61c4d54c4d0a/Analyses/Basecall_1D_000/BaseCalled_template/Move Dataset {8386}
/read_d5df4431-8315-4983-835a-61c4d54c4d0a/Analyses/Basecall_1D_000/BaseCalled_template/Trace Dataset {8386, 8}
/read_d5df4431-8315-4983-835a-61c4d54c4d0a/Analyses/Basecall_1D_000/Summary Group
/read_d5df4431-8315-4983-835a-61c4d54c4d0a/Analyses/Basecall_1D_000/Summary/basecall_1d_template Group
/read_d5df4431-8315-4983-835a-61c4d54c4d0a/Analyses/Segmentation_000 Group
/read_d5df4431-8315-4983-835a-61c4d54c4d0a/Analyses/Segmentation_000/Summary Group
/read_d5df4431-8315-4983-835a-61c4d54c4d0a/Analyses/Segmentation_000/Summary/segmentation Group
/read_d5df4431-8315-4983-835a-61c4d54c4d0a/Raw Group
/read_d5df4431-8315-4983-835a-61c4d54c4d0a/Raw/Signal Dataset {16861/Inf}
/read_d5df4431-8315-4983-835a-61c4d54c4d0a/channel_id Group
/read_d5df4431-8315-4983-835a-61c4d54c4d0a/context_tags Group
/read_d5df4431-8315-4983-835a-61c4d54c4d0a/tracking_id Group


How do I change these reads to be recognizable.

**Comment by liu2005678** [comment]
solved by using h5copy， thanks。

**Comment by lemonsky123** [comment]
> solved by using h5copy， thanks。

Hi, @liu2005678 , I also met the same error, some of my reads could not find channels by Deepmod. Could you please show me the commands you used with h5copy? Thanks so much!
Best.

**Comment by liu2005678** [comment]
h5copy provided by the hdf5 group seem to be less efficiency. I made it by Python h5py API.  
The  scripts used:

import pandas as pd  
import re
import h5py  

reads_info = pd.read_csv('E:/folder/sequencing_summary.txt', sep='\t')  # read in the sequencing summary, as each fast5 had different reads ids.   the  read_d5df4431-8315-...

b=re.compile('_|\.')
d=[]
filename=[]
read_id=[]
for i in reads_info['read_id']:
    read_id.append(i)
for i in reads_info['filename']:
    filename.append(i)
    c=b.split(i)
    d.append(c[2])

for i in range(len(reads_info)):
    file_path='F:/fast6/'+ reads_info['filename'][i]    #the fast5 read in 
    file_write='d:\\PF427\\'+reads_info['filename'][i]   # the fast5 to be written
    #print(file_path)
    f2=h5py.File(file_path,'r')
    analysis="read_"+read_id[i] + "/Analyses"
    raw="read_"+read_id[i] + "/Raw/Signal"
    raw2="/Raw/Reads/Read_"+d[i]
    channel_id="read_"+read_id[i] +"/channel_id"
    context_tags="read_"+read_id[i] +"/context_tags"
    tracking_id="read_"+read_id[i] +"/tracking_id"
    f3=h5py.File(file_write,'w')
    f2.copy(analysis, f3)
    grp1=f3.create_group(raw2)
    grp2=f3.create_group("/UniqueGlobalKey")
    f2.copy(raw,grp1)
    f2.copy(channel_id,grp2)
    f2.copy(context_tags,grp2)
    f2.copy(tracking_id,grp2)
    f2.close()
    f3.close()

**Comment by lemonsky123** [comment]
> h5copy provided by the hdf5 group seem to be less efficiency. I made it by Python h5py API.
> The scripts used:
> 
> import pandas as pd
> import re
> import h5py
> 
> reads_info = pd.read_csv('E:/folder/sequencing_summary.txt', sep='\t') # read in the sequencing summary, as each fast5 had different reads ids. the read_d5df4431-8315-...
> 
> b=re.compile('_|.')
> d=[]
> filename=[]
> read_id=[]
> for i in reads_info['read_id']:
> read_id.append(i)
> for i in reads_info['filename']:
> filename.append(i)
> c=b.split(i)
> d.append(c[2])
> 
> for i in range(len(reads_info)):
> file_path='F:/fast6/'+ reads_info['filename'][i] #the fast5 read in
> file_write='d:\PF427\'+reads_info['filename'][i] # the fast5 to be written
> #print(file_path)
> f2=h5py.File(file_path,'r')
> analysis="read_"+read_id[i] + "/Analyses"
> raw="read_"+read_id[i] + "/Raw/Signal"
> raw2="/Raw/Reads/Read_"+d[i]
> channel_id="read_"+read_id[i] +"/channel_id"
> context_tags="read_"+read_id[i] +"/context_tags"
> tracking_id="read_"+read_id[i] +"/tracking_id"
> f3=h5py.File(file_write,'w')
> f2.copy(analysis, f3)
> grp1=f3.create_group(raw2)
> grp2=f3.create_group("/UniqueGlobalKey")
> f2.copy(raw,grp1)
> f2.copy(channel_id,grp2)
> f2.copy(context_tags,grp2)
> f2.copy(tracking_id,grp2)
> f2.close()
> f3.close()

Thanks very much!
Best.

**Comment by liu2005678** [comment]
commands of  h5copy....

h5copy -i "FAN03738_2139a5cc_0.fast5" -o "2_FAN03738_2139a5cc_0.fast5" -s "/read_d33822ee-1daf-4ff4-bcf4-a2e6881479f1/Analyses"  -d "/Analyses"

h5copy -p -i "FAN03738_2139a5cc_0.fast5" -o "2_FAN03738_2139a5cc_0.fast5" -s "/read_d33822ee-1daf-4ff4-bcf4-a2e6881479f1/Raw/Signal"  -d "/Raw/Reads/Read_1/Signal"

h5copy -p -i "FAN03738_2139a5cc_0.fast5" -o "2_FAN03738_2139a5cc_0.fast5" -s "/read_d33822ee-1daf-4ff4-bcf4-a2e6881479f1/channel_id"  -d "/UniqueGlobalKey/channel_id"

h5copy -i "FAN03738_2139a5cc_0.fast5" -o "2_FAN03738_2139a5cc_0.fast5" -s "/read_d33822ee-1daf-4ff4-bcf4-a2e6881479f1/context_tags"  -d "/UniqueGlobalKey/context_tags"

h5copy -i "FAN03738_2139a5cc_0.fast5" -o "2_FAN03738_2139a5cc_0.fast5" -s "/read_d33822ee-1daf-4ff4-bcf4-a2e6881479f1/tracking_id"  -d "/UniqueGlobalKey/tracking_id"




h5copy -i "FAN03738_2139a5cc_1.fast5" -o "2_FAN03738_2139a5cc_1.fast5" -s "/read_37c95b46-28ce-4d46-8f29-c49a1620db44/Analyses"  -d "/Analyses"
h5copy -p -i "FAN03738_2139a5cc_1.fast5" -o "2_FAN03738_2139a5cc_1.fast5" -s "/read_37c95b46-28ce-4d46-8f29-c49a1620db44/Raw/Signal"  -d "/Raw/Reads/Read_2/Signal"
h5copy -p -i "FAN03738_2139a5cc_1.fast5" -o "2_FAN03738_2139a5cc_1.fast5" -s "/read_37c95b46-28ce-4d46-8f29-c49a1620db44/channel_id"  -d "/UniqueGlobalKey/channel_id"
h5copy -i "FAN03738_2139a5cc_1.fast5" -o "2_FAN03738_2139a5cc_1.fast5" -s "/read_37c95b46-28ce-4d46-8f29-c49a1620db44/context_tags"  -d "/UniqueGlobalKey/context_tags"
h5copy -i "FAN03738_2139a5cc_1.fast5" -o "2_FAN03738_2139a5cc_1.fast5" -s "/read_37c95b46-28ce-4d46-8f29-c49a1620db44/tracking_id"  -d "/UniqueGlobalKey/tracking_id"

**Comment by lemonsky123** [comment]
> commands of h5copy....
> 
> h5copy -i "FAN03738_2139a5cc_0.fast5" -o "2_FAN03738_2139a5cc_0.fast5" -s "/read_d33822ee-1daf-4ff4-bcf4-a2e6881479f1/Analyses" -d "/Analyses"
> 
> h5copy -p -i "FAN03738_2139a5cc_0.fast5" -o "2_FAN03738_2139a5cc_0.fast5" -s "/read_d33822ee-1daf-4ff4-bcf4-a2e6881479f1/Raw/Signal" -d "/Raw/Reads/Read_1/Signal"
> 
> h5copy -p -i "FAN03738_2139a5cc_0.fast5" -o "2_FAN03738_2139a5cc_0.fast5" -s "/read_d33822ee-1daf-4ff4-bcf4-a2e6881479f1/channel_id" -d "/UniqueGlobalKey/channel_id"
> 
> h5copy -i "FAN03738_2139a5cc_0.fast5" -o "2_FAN03738_2139a5cc_0.fast5" -s "/read_d33822ee-1daf-4ff4-bcf4-a2e6881479f1/context_tags" -d "/UniqueGlobalKey/context_tags"
> 
> h5copy -i "FAN03738_2139a5cc_0.fast5" -o "2_FAN03738_2139a5cc_0.fast5" -s "/read_d33822ee-1daf-4ff4-bcf4-a2e6881479f1/tracking_id" -d "/UniqueGlobalKey/tracking_id"
> 
> h5copy -i "FAN03738_2139a5cc_1.fast5" -o "2_FAN03738_2139a5cc_1.fast5" -s "/read_37c95b46-28ce-4d46-8f29-c49a1620db44/Analyses" -d "/Analyses"
> h5copy -p -i "FAN03738_2139a5cc_1.fast5" -o "2_FAN03738_2139a5cc_1.fast5" -s "/read_37c95b46-28ce-4d46-8f29-c49a1620db44/Raw/Signal" -d "/Raw/Reads/Read_2/Signal"
> h5copy -p -i "FAN03738_2139a5cc_1.fast5" -o "2_FAN03738_2139a5cc_1.fast5" -s "/read_37c95b46-28ce-4d46-8f29-c49a1620db44/channel_id" -d "/UniqueGlobalKey/channel_id"
> h5copy -i "FAN03738_2139a5cc_1.fast5" -o "2_FAN03738_2139a5cc_1.fast5" -s "/read_37c95b46-28ce-4d46-8f29-c49a1620db44/context_tags" -d "/UniqueGlobalKey/context_tags"
> h5copy -i "FAN03738_2139a5cc_1.fast5" -o "2_FAN03738_2139a5cc_1.fast5" -s "/read_37c95b46-28ce-4d46-8f29-c49a1620db44/tracking_id" -d "/UniqueGlobalKey/tracking_id"

Got it. Thanks!
Best.

**Comment by skerker** [comment]
I have a similar problem with events data being in the wrong place for DeepMod to find it.  Is h5copy the best solution, or is it possible to redo the basecalling with guppy in a way that puts things in the right locations?    

Here is an example of my fast5 file:

(base) -bash-4.1$ h5ls -r 3fe3dea6-8608-4cc2-ab42-2e5510043e23.fast5
/                        Group
/Analyses                Group
/Analyses/Basecall_1D_000 Group
/Analyses/Basecall_1D_000/Summary Group
/Analyses/Basecall_1D_001 Group
/Analyses/Basecall_1D_001/BaseCalled_template Group
**/Analyses/Basecall_1D_001/BaseCalled_template/Fastq Dataset {SCALAR}**
/Analyses/Basecall_1D_001/BaseCalled_template/Move Dataset {48977}
/Analyses/Basecall_1D_001/BaseCalled_template/Trace Dataset {48977, 8}
/Analyses/Basecall_1D_001/Summary Group
/Analyses/Basecall_1D_001/Summary/basecall_1d_template Group
/Analyses/RawGenomeCorrected_000 Group
/Analyses/RawGenomeCorrected_000/BaseCalled_template Group
/Analyses/RawGenomeCorrected_000/BaseCalled_template/Alignment Group
**/Analyses/RawGenomeCorrected_000/BaseCalled_template/Events Dataset {6749}**
/Analyses/Segmentation_000 Group
/Analyses/Segmentation_000/Summary Group
/Analyses/Segmentation_001 Group
/Analyses/Segmentation_001/Summary Group
/Analyses/Segmentation_001/Summary/segmentation Group
/Raw                     Group
/Raw/Reads               Group
/Raw/Reads/Read_13987    Group
/Raw/Reads/Read_13987/Signal Dataset {98157/Inf}
/UniqueGlobalKey         Group
/UniqueGlobalKey/channel_id Group
/UniqueGlobalKey/context_tags Group
/UniqueGlobalKey/tracking_id Group

**Comment by liuqianhn** [comment]
@skerker  I see you have both move table and fastq under `/Analyses/Basecall_1D_001/BaseCalled_template/`. You can use move data after you set `--move 1`. Please note that you also need to set `--basecall_1d Basecall_1D_001` since the default value of `basecall_1d` is `Basecall_1D_000`.

**Comment by skerker** [comment]
Thank you!  

I set --move and --basecall_1d Basecall_1D_001 and now it is running.

**Comment by liuqianhn** [comment]
@skerker Great. Please also note that the event data you hightlighted is generated by `Nanoraw` or `Tombo` rather than by basecaller and thus might be wrong for DeepMod.

**Comment by skerker** [comment]
OK thanks.  Yes, I ran tombo resquiggle on this - which generated that events table, which I guess is the wrong thing for DeepMod.

But the move table is from my guppy basecaller run.  So I think I'm OK for deepmod, using --move and --basecall_1d Basecall_1D_001?

**Comment by zcWang0591** [comment]
> Basecall_1D_000
Hi, I have a question about Basecall_1D_000 and Basecall_1D_001, what is the difference between them? Should I do something to check the base-calling result in this two parts are right, otherwise DeepMod will meet some problems?

**Comment by liuqianhn** [comment]
The difference between Basecall_1D_000 and Basecall_1D_001: sometimes, you might baseball the data twice, and both are in the fast5 files, and they are list with different Basecall_1D ids. You need to check your several fast5 files to see which one you have. Usually, it is Basecall_1D_000.

**Comment by liuqianhn** [comment]
Closed due to no recent response. Feel free to reopen it if you need more help.
