### ISSUE TITLE
On version of tensorflow

### ISSUE THREAD

**Issue by orangehe** [WGLab/DeepMod#30]
The installation guide page does not mention the version of tensorflow. I read the source code and find that Deepmod uses the tf.contrib api. It seems that tf.contrib has been deprecated since tensorflow 1.13, so i guess the proper version of tensorflow might be 1.13. Is that right?

**Comment by liuqianhn** [comment]
Hi @orangehe , yes, you are right. I will update the installation guidance and we will update the code in future. Thanks.

**Comment by liuqianhn** [comment]
closed due to no recent activities.
