### ISSUE TITLE
Does the model support using move table?

### ISSUE THREAD

**Issue by vahidAK** [WGLab/DeepMod#33]
Hi @liuqianhn 
I realized that DeepMod supports move table. Does it consistent with your trained model?, as you trained them on events detected by Albacore
I assume that the segmentation and event detection algorithm of guppy might have some differences with albacore.

Thanks,
Vahid.

**Comment by liuqianhn** [comment]
@vahidAK DeepMod supports move table now, but we do not have the re-trained models on the move table so far. I think that the segmentation of event detections in guppy and albacore might be different but would not have a significant difference. However, I have no data to confirm this yet. Please feel free to share what you find if you test trained models on move table. Thanks.

**Comment by liuqianhn** [comment]
Closed due to no recent response. Feel free to reopen it if you need more help.
