### ISSUE TITLE
Evaluation of Na12878 dataset

### ISSUE THREAD

**Issue by zcWang0591** [WGLab/DeepMod#36]
Hi Liu:
I am working on the problem about 5mc/6ma base modification in human brain. I have tried the pipeline that you recommend on Na12878 dataset(https://github.com/WGLab/DeepMod/blob/master/docs/Reproducibility.md), but for the last step, I just see the guidance for data downloading, is there any scripts for doing the evaluation of Na12878 dataset？Can you write a brief guidance for it?
Many thanks.

**Comment by liuqianhn** [comment]
@zcWang0591 You need to download the bisulfite sequencing data for the evaluation. We have been working on the script for the evaluation with no hard-code paths. We hope we can upload it soon. The process is that: firstly, get the completely methylated CG (with methylation percentage >=90% in both replicates of bisulfite sequencing) and completely un-methylated CG (with methylation percentage 0% in both replicates), and then check them against the prediction with prediction methylation percentage. AP and AUC can be plotted by python tools.

**Comment by zcWang0591** [comment]
Thank you for replying. Another question is about the E. coli dataset, do you have a download URL of it? I have emailed the original authors according to your guidance, but not gotten reply until now, which makes me hard to reproduce the result. So can you provide a download URL for it?
Many thanks.

**Comment by liuqianhn** [comment]
For the UMR and SSS E. Coli data, you can find where to download the data from https://www.nature.com/articles/nmeth.4184. For other E. coli data, you need to contact the developer of [nanoraw](https://github.com/marcus1487/nanoraw).

**Comment by zcWang0591** [comment]
Hi, It is a problem that nanoraw seems not have public dataset?(https://github.com/nanoporetech/tombo/issues/248). Do I miss something? can you give a brief guidance for download this part of data?

**Comment by liuqianhn** [comment]
@zcWang0591 I see the issue. I wish I could provide you some download guidance, but there is no brief guidance for downloading, and you can only get the downloading information from the developer of the nanoraw.

**Comment by zcWang0591** [comment]
Hi, if I only have the E. coli data from https://www.nature.com/articles/nmeth.4184, does the pipeline for the analysis of E. coli data keep the same? I have read the examples of pipeline(https://github.com/WGLab/DeepMod/blob/master/docs/Reproducibility.md), but it seems a guidance for the data of nanoraw? Can you write a brief guidance for the pipeline of the data which not produced by nanoraw? Because it is hard for me to get that part of data.
Many thanks.

**Comment by liuqianhn** [comment]
It is same if you use E. coli data from https://www.nature.com/articles/nmeth.4184: you can see UMR as negative control and SSS as positive control. But please note that some models are trained on UMR and SSS.

**Comment by zcWang0591** [comment]
Thank you for replying, there is one thing that I want to confirm, SSS means the methylation introduced by M.SssI? I have read the paper, but not find SSS.

**Comment by liuqianhn** [comment]
Yes, SSS is short for the methylation introduced by M.Sssl. Thanks for pointing this out.

**Comment by zcWang0591** [comment]
Thank you, I will try your suggestions

**Comment by liuqianhn** [comment]
Closed due to no recent response. Feel free to reopen it if you need more help.
