### ISSUE TITLE
How to filter results?

### ISSUE THREAD

**Issue by qiuyixmm** [WGLab/DeepMod#37]
Hello ,
    In my output file resulting from DeepMod, the methylation coverages of many sites were 0. So the mehylation percentage of these corresponding sites were also equal to 0. Should I remove these sites in which methylation coverages and mehylation percentage were both 0 ?
    In addition, it is necessary to filter real coverages and (or) methylation coverages to obtain more reliable methylated sites? If so, what are suitable cutoff values of real coverages and (or) methylation coverages that you would recommend ?
    Thanks!

**Comment by liuqianhn** [comment]
@qiuyixmm sorry for the late reply. In the output from DeepMod, there are some reference positions with 0 methylation coverage. It is not necessary to filter them if the coverage is large enough. According to the experience, you can set methylation percentages to 0.1 or 0.15 to have more reliable methylated sites, and it would be better if the coverage is higher, such as >10 or >20. The parameters depend on whether you can have enough methylated sites for further analysis. Please note that this is my experience, and I do not fully evaluate those parameters.

**Comment by qiuyixmm** [comment]
@liuqianhn  whether these reference positions with 0 methylation coverage can be considered as the methylated sites or not ?

**Comment by liuqianhn** [comment]
If the total coverage is large enough, 0 methylation coverage means un-methylated sites.

**Comment by liuqianhn** [comment]
Closed due to no recent response. Feel free to reopen it if you need more help.
