### ISSUE TITLE
Deepmod-GPU

### ISSUE THREAD

**Issue by Marozi2** [WGLab/DeepMod#38]
Hello,

I ran DeepMod on the region 5 000 000 - 10 000 000 of the Human chromosome 20. I did It on CPUs and it took me 1 hour. Then I tried the same run but on GPU and so with the same installation except for tensorflow-gpu. I was expecting to be faster on GPUs. Actually, it takes 2h30 on the GPUs. So my questions are; is DeepMod able to take advantage of the GPUs? Is it normal to have such result?
The command I used to run DeepMod: 
`#!/bin/bash
#SBATCH --job-name=deepmod_MethCall
#SBATCH --gpus=2
#SBATCH --mem=45000
#SBATCH --cpus-per-gpu=20
#SBATCH --time=05:00:00
#SBATCH --partition=gpu
#SBATCH --output=/CECI/home/ulg/genhum/thissen/slurm_files/slurm-%j-deepmod.out

module load Python/3.7.4-GCCcore-8.3.0

srun singularity exec --bind /CECI/home/ulg/genhum/thissen --nv /CECI/home/ulg/genhum/thissen/methylation/deepmod/deepmod_gpu_nvidia-based-2020-07-23-4c83937316b7.simg \
python /usr/local/bin/DeepMod.py detect --wrkBase fast5_files_albacore/workspace/pass/0 --Ref /CECI/home/ulg/genhum/thissen/data/brut/methylation/reference.fasta --FileID deepmod_methylation_call --modfile /tools/DeepMod/train_deepmod/rnn_conmodC_P100wd21_f7ne1u0_4/mod_train_conmodC_P100wd21_f3ne1u0 --threads 15 --outFolder .`

Thanks!

**Comment by liuqianhn** [comment]
@Marozi2 Thanks for testing DeepMod on both CPU and GPU. I do not expect faster run on GPU, and the reason is simple: the bottleneck here should be the larger data through IO rather than the processing time itself. Thus, if you have multiple processors, a run with more threads can be done faster (Please also check the potential memory issues).

**Comment by liuqianhn** [comment]
Closed due to no recent response. Feel free to reopen it if you need more help.
