### ISSUE TITLE
What are 7th-9th columns in the output?

### ISSUE THREAD

**Issue by PanZiwei** [WGLab/DeepMod#40]
Hi, 
I checked the [result explanation](https://github.com/WGLab/DeepMod/blob/master/docs/Results_explanation.md) for the output file, but I still have questions on the column meanings. Can you tell more about the 7th-9th columns(148655 148656 0,0,0) especially the 9th column? 

Thank you so much for your help!

**Comment by liuqianhn** [comment]
@PanZiwei I think you can ignore these columns for now and column 9 is not meaningful, since I tried to make the output compatible with BED format using them.  Sorry for the confusion.

**Comment by PanZiwei** [comment]
Hi @liuqianhn ,
Thank you so much for the quick response. 
I have one more question on the 8th column `Methylation percentage` in the output file. Does methylation percentage show the methylation frequencies at the CpG site? Is it measured at the genome level or per-read level?

Thanks!

**Comment by liuqianhn** [comment]
@PanZiwei `Methylation percentage` is not in the 8th column but in the last second column. The percentage is for a C at a CpG site, and thus it summarizes all methylations of all long reads whose bases are aligned against this site: it is calculated by the number of methylation prediction at this site divided by the total number of reads aligned against this site. Per-read level prediction is in intermediate files.
