### ISSUE TITLE
Installation problems in 2023

### ISSUE THREAD

**Issue by anish-taori** [WGLab/DeepMod#61]
I am trying to install DeepMod in 2023 but I am facing many errors as the packages have been updated since DeepMod's release. I am trying to downgrade everything to specified versions. Has an updated DeepMod been released since? If there is someone who has installed and used DeepMod recently, could you please reply on this issue. I am still in college,and would really appreciate any help.

**Comment by anish-taori** [comment]
got to knwo about DeepMod2

**Comment by liuqianhn** [comment]
@anish-taori Please use DeepMod2.
