### ISSUE TITLE
Question about the version and reference of this software.

### ISSUE THREAD

**Issue by DAVID2022** [WGLab/DeepMod#7]
Hi,
    I am trying to find a suitable software to conduct a research in the field of epigenetics based on myONT data. I cannot find your paper (Detection of DNA base modifications by deep recurrent neural network on Oxford Nanopore sequencing data) about this software on scholar.google, can you tell me why? Can I have a look on that paper now?
    Is the software presented here the latest version that used in your paper?
    Best wishes,
    David.

**Comment by kaichop** [comment]
It is the latest version. It is not yet published but hopefully soon.

**Comment by DAVID2022** [comment]
Thank you very much for your help! 
Wish to see this paper soon.
