### ISSUE TITLE
The choice of modfile

### ISSUE THREAD

**Issue by DAVID2022** [WGLab/DeepMod#8]
Hi,
 If I want to try your software on the research of some other organism, which modfile should I choose? rnn_f7_wd21_chr1to10_4 or rnn_conmodC_P100wd21_f7ne1u0_4?
Best wishes,
David.

**Comment by liuqianhn** [comment]
Hi @DAVID2022 , could you please describe more about the basealling of your data and which type of modification you will study? Thank you.

**Comment by DAVID2022** [comment]
We perform realtime basealling using guppy-2.0.10 on PromethION and we want to analysis both 6mA and 5mc modiﬁcations using your great softwre on our organism.

**Comment by liuqianhn** [comment]
Hi @DAVID2022 , in the updated basecalling in PromethoION, there are two issues you might meet later: (1) please check whether `events` are available in fast5 files, if no, basecalling with events information might needed. (2) please check whether a fast5 file contains a single read or multiple reads, if multiple reads, you might need to use the tool from "https://github.com/nanoporetech/ont_fast5_api" for converting multif-fast5 format to single-fast format.

For 5mC, after basecalling using albacore v2.3+, you can use `rnn_f7_wd21_chr1to10_4`. There is only one model for 6mA. 

Feel free to let me know if you have any issue to use this tool.

**Comment by DAVID2022** [comment]
Thank you very much ! I will try it instantly.

**Comment by DAVID2022** [comment]
We perform realtime basealling using guppy-2.0.10 with default parameters. How can I make sure is there any events information in fast5 files ? Should I use some special tools to check that?

**Comment by liuqianhn** [comment]
H5dump can be used to check all information in fast5. Please note that h5dump print fast5 content to screen.

**Comment by DAVID2022** [comment]
![image](https://user-images.githubusercontent.com/45761661/58617933-ef011480-82f3-11e9-8314-6366d5af2683.png)
I cannot find any information about events in my fast5 file, So to get those events information ,Is there any parameter should I set on MinKNOW?

**Comment by liuqianhn** [comment]
You might use case insensitive in grep. It seems events generation might be not supported durning new Nanopore machine(not sure what your Nanopore software versions). But you can use albacore with one of option value equal to “fastq,fast5” to re-baseball with events.

**Comment by DAVID2022** [comment]
![image](https://user-images.githubusercontent.com/45761661/58621017-04c60800-82fb-11e9-8002-e217f97d3fb1.png)
I still cannot find any information about events in my fast5 file using case insensitive in grep. So if I use guppy(v3.1.5) which is the latest basecaller of ONT to carry on basecalling, I cannot get the events information deepmod need ?

**Comment by liuqianhn** [comment]
Hi @DAVID2022 , the message shows there is no event in the fast5 file. You might use albacore v2.3+ re-basecall fast5 files.

**Comment by DAVID2022** [comment]
Thank you very much for your kind help! I will try to basecalling my data with albacore. Considering the higher speed and accuracy of guppy, hope to see you great software be compatible with guppy soon!

**Comment by DAVID2022** [comment]
When I try to run deepmod on my data in this way:
python /public1/home/pg3152/DeepMod/bin/DeepMod.py detect --wrkBase /public1/home/pg3152/DAVID/TASK22-3gMETH/NANO19/davidDATA/20190203-NPL0651-P1-A11-D11/1-A11-D11/reads/0.tar --Ref /public1/home/pg3152/DAVID/TASK22-3gMETH/NANO19/davidDATA/deepmod/data/david-david-REFERENCE-1.0.fa --outFolder /public1/home/pg3152/DAVID/TASK22-3gMETH/NANO19/davidDATA/deepmod/data --Base C --modfile /public1/home/pg3152/DeepMod/train_mod/rnn_f7_wd21_chr1to10_4/mod_train_f7_wd21_chr1to10 --FileID david_tar0 --threads 6

I got some error information :

Nanopore sequencing data analysis is resourece-intensive and time consuming.
Some potential strong recommendations are below:
	If your reference genome is large as human genome and your Nanopore data is huge,
	It would be faster to run this program parallelly to speed up.
	You might run different input folders of your fast5 files and
	give different output names (--FileID) or folders (--outFolder)
	A good way for this is to run different chromosome individually.

             Current directory: /public1/home/pg3152/DAVID/TASK22-3gMETH/NANO19/davidDATA/deepmod/process
                      outLevel: 2
                       wrkBase: /public1/home/pg3152/DAVID/TASK22-3gMETH/NANO19/davidDATA/20190203-NPL0651-P1-A11-D11/1-A11-D11/reads/0.tar
                        FileID: david_tar0
                     outFolder: /public1/home/pg3152/DAVID/TASK22-3gMETH/NANO19/davidDATA/deepmod/data/
                     recursive: 1
              files_per_thread: 1000
                       threads: 6
                    windowsize: 21
                      alignStr: minimap2
                   basecall_1d: Basecall_1D_000
              basecall_2strand: BaseCalled_template
                        ConUnk: True
                   outputlayer:
                          Base: C
                   mod_cluster: 0
                       predDet: 1
                           Ref: /public1/home/pg3152/DAVID/TASK22-3gMETH/NANO19/davidDATA/deepmod/data/david-david-REFERENCE-1.0.fa
                          fnum: 7
                        hidden: 100
                       modfile: /public1/home/pg3152/DeepMod/train_mod/rnn_f7_wd21_chr1to10_4/mod_train_f7_wd21_chr1to10
                        region: [[None, None, None]]
Total files=0
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /public1/home/pg3152/DeepMod/bin/scripts/myMultiBiRNN.py:42: BasicLSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /public1/home/pg3152/DeepMod/bin/scripts/myMultiBiRNN.py:42: BasicLSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /public1/home/pg3152/DeepMod/bin/scripts/myMultiBiRNN.py:42: BasicLSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /public1/home/pg3152/DeepMod/bin/scripts/myMultiBiRNN.py:42: BasicLSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /public1/home/pg3152/DeepMod/bin/scripts/myMultiBiRNN.py:42: BasicLSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /public1/home/pg3152/DeepMod/bin/scripts/myMultiBiRNN.py:42: BasicLSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /public1/home/pg3152/DeepMod/bin/scripts/myMultiBiRNN.py:42: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /public1/home/pg3152/DeepMod/bin/scripts/myMultiBiRNN.py:42: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /public1/home/pg3152/DeepMod/bin/scripts/myMultiBiRNN.py:42: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /public1/home/pg3152/DeepMod/bin/scripts/myMultiBiRNN.py:42: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /public1/home/pg3152/DeepMod/bin/scripts/myMultiBiRNN.py:42: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /public1/home/pg3152/DeepMod/bin/scripts/myMultiBiRNN.py:42: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From /public1/home/pg3152/DeepMod/bin/scripts/myMultiBiRNN.py:47: static_bidirectional_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell, unroll=True))`, which is equivalent to this API
WARNING:tensorflow:From /public1/home/pg3152/DeepMod/bin/scripts/myMultiBiRNN.py:47: static_bidirectional_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell, unroll=True))`, which is equivalent to this API
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py:1565: static_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removedin a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell, unroll=True)`, which is equivalent to this API
WARNING:tensorflow:From /public1/home/pg3152/DeepMod/bin/scripts/myMultiBiRNN.py:47: static_bidirectional_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell, unroll=True))`, which is equivalent to this API
WARNING:tensorflow:From /public1/home/pg3152/DeepMod/bin/scripts/myMultiBiRNN.py:47: static_bidirectional_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell, unroll=True))`, which is equivalent to this API
WARNING:tensorflow:From /public1/home/pg3152/DeepMod/bin/scripts/myMultiBiRNN.py:47: static_bidirectional_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell, unroll=True))`, which is equivalent to this API
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py:1565: static_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removedin a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell, unroll=True)`, which is equivalent to this API
WARNING:tensorflow:From /public1/home/pg3152/DeepMod/bin/scripts/myMultiBiRNN.py:47: static_bidirectional_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell, unroll=True))`, which is equivalent to this API
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py:1565: static_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removedin a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell, unroll=True)`, which is equivalent to this API
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py:1565: static_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removedin a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell, unroll=True)`, which is equivalent to this API
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py:1565: static_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removedin a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell, unroll=True)`, which is equivalent to this API
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py:1565: static_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removedin a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell, unroll=True)`, which is equivalent to this API
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/ops/metrics_impl.py:526: to_float (from tensorflow.python.ops.math_ops) is deprecated and willbe removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/ops/metrics_impl.py:526: to_float (from tensorflow.python.ops.math_ops) is deprecated and willbe removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/ops/metrics_impl.py:526: to_float (from tensorflow.python.ops.math_ops) is deprecated and willbe removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/ops/metrics_impl.py:788: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/ops/metrics_impl.py:788: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/ops/metrics_impl.py:526: to_float (from tensorflow.python.ops.math_ops) is deprecated and willbe removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/ops/metrics_impl.py:788: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/ops/metrics_impl.py:526: to_float (from tensorflow.python.ops.math_ops) is deprecated and willbe removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/ops/metrics_impl.py:788: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/ops/metrics_impl.py:788: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/ops/metrics_impl.py:526: to_float (from tensorflow.python.ops.math_ops) is deprecated and willbe removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/ops/metrics_impl.py:788: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
2019-05-30 21:16:08.429202: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2500035000 Hz
2019-05-30 21:16:08.429427: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2500035000 Hz
2019-05-30 21:16:08.429511: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2500035000 Hz
2019-05-30 21:16:08.429612: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2500035000 Hz
2019-05-30 21:16:08.429648: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2500035000 Hz
2019-05-30 21:16:08.429673: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2500035000 Hz
2019-05-30 21:16:08.467710: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5649ddf5f500 executing computations on platform Host. Devices:
2019-05-30 21:16:08.467723: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5649ddf5f6a0 executing computations on platform Host. Devices:
2019-05-30 21:16:08.467739: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5649ddf5fdd0 executing computations on platform Host. Devices:
2019-05-30 21:16:08.467743: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5649ddf5f7b0 executing computations on platform Host. Devices:
2019-05-30 21:16:08.467752: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5649ddf5f580 executing computations on platform Host. Devices:
2019-05-30 21:16:08.467758: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5649ddf5f440 executing computations on platform Host. Devices:
2019-05-30 21:16:08.478697: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-05-30 21:16:08.478708: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-05-30 21:16:08.478717: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-05-30 21:16:08.478725: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-05-30 21:16:08.478733: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-05-30 21:16:08.478739: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-05-30 21:16:09.175632: W tensorflow/core/graph/graph_constructor.cc:1272] Importing a graph with a lower producer version 26 into an existing graph with producer version 27. Shape inference will have run different parts of the graph with different producer versions.
2019-05-30 21:16:09.175618: W tensorflow/core/graph/graph_constructor.cc:1272] Importing a graph with a lower producer version 26 into an existing graph with producer version 27. Shape inference will have run different parts of the graph with different producer versions.
2019-05-30 21:16:09.181186: W tensorflow/core/graph/graph_constructor.cc:1272] Importing a graph with a lower producer version 26 into an existing graph with producer version 27. Shape inference will have run different parts of the graph with different producer versions.
2019-05-30 21:16:09.181422: W tensorflow/core/graph/graph_constructor.cc:1272] Importing a graph with a lower producer version 26 into an existing graph with producer version 27. Shape inference will have run different parts of the graph with different producer versions.
2019-05-30 21:16:09.182175: W tensorflow/core/graph/graph_constructor.cc:1272] Importing a graph with a lower producer version 26 into an existing graph with producer version 27. Shape inference will have run different parts of the graph with different producer versions.
2019-05-30 21:16:09.192729: W tensorflow/core/graph/graph_constructor.cc:1272] Importing a graph with a lower producer version 26 into an existing graph with producer version 27. Shape inference will have run different parts of the graph with different producer versions.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
WARNING:tensorflow:From /public1/home/pg3152/anaconda2/envs/mdeepmod/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Per-read Prediction consuming time 14
Find: /public1/home/pg3152/DAVID/TASK22-3gMETH/NANO19/davidDATA/deepmod/data//david_tar0 0 rnn.pred.ind
[]
Genomic-position Detection consuming time 0

Can you tell me why?

**Comment by liuqianhn** [comment]
Hi @DAVID2022 , DeepMod cannot support .tar now. I would add this in a later version.

**Comment by DAVID2022** [comment]
Thank you！I will retry my data.

**Comment by DAVID2022** [comment]
Hi,
Will the "move table" produced by Guppy (v2.3.1 and newer) can be used to support the analysis of Deepmod as the same role of  the old "event table" produced by albacore? As Oxford Nanopore Technologies  said, " The move table contains just the 'Move' column for the old event table: it shows how much the basecall moved at a given block index." ( https://community.nanoporetech.com/posts/guppy-2-3-1-release)
Best wishes,
David.
