### ISSUE TITLE
The compatibility of basecaller ?

### ISSUE THREAD

**Issue by DAVID2022** [WGLab/DeepMod#9]
Hi,
Can the "move table" produced by Guppy (v2.3.1 and newer) be used to support the analysis of Deepmod as the same role of the old "event table" produced by albacore? As Oxford Nanopore Technologies said, " The move table contains just the 'Move' column for the old event table: it shows how much the basecall moved at a given block index." ( https://community.nanoporetech.com/posts/guppy-2-3-1-release)
Best wishes,
David.

**Comment by liuqianhn** [comment]
Hi @DAVID2022 , I have no "move table" data available now. I have been working on it to make DeepMod to support it. If you can send a fast5 with "move table" to liuqianhn@hotmail.com, it would speed up the process to answer your questions. Thank you.

**Comment by DAVID2022** [comment]
Sure, I will send you some data with "move table" produced by Guppy-v3.1.5 after I finish the process of  basecalling.

**Comment by DAVID2022** [comment]
Hi,
  I have already sent those data to you through my email "canamaster2022@gmail.com"，please check your mailbox at your convenience.

**Comment by liuqianhn** [comment]
Hi @DAVID2022 , Thank you. I will check this data.

**Comment by liuqianhn** [comment]
Hi @DAVID2022 , I checked the data: DeepMod cannot handle "move" table. I will improve the DeepMod to support it. Thank you.

**Comment by DAVID2022** [comment]
Thank you for your kind help! Looking forward to your new version software.
